version: '3'
services:
  backend:
    build:
      context: ./vimeet-server
  frontend:
    build:
      context: ./vimeet-lets-go
      args:
        - VIMEET_SERVER_ADDRESS=localhost:8080\/api
    depends_on:
      - backend
  proxy:
    build:
      context: ./proxy
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:80
